config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
 
  get '/admins/page', to: 'admins#page', as: 'admins_page'
  resources :questions
  resource :session, only: %i[new create destroy]
  resources :users do
    member do
      put 'admin_update_role'
    end
  end
  resource :profile, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
  end
  

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 0, admin: 1 }
  attribute :role, :integer, default: 0
  
  has_secure_password

  has_many :questions, dependent: :destroy

  validates :email, presence: true, uniqueness: true
   
  has_one :profile, dependent: :destroy

  before_save :downcase_nickname

  def downcase_nickname
    nickname.downcase!
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def page
    @users = User.all
  end

  def create
    # Ваш код для створення адміністратора
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user   
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[update destroy show edit]

  def create
    @question = Question.new(question_params)

    if @question.user_id.blank?
      @question.user_id = current_user.id
    end

    if @question.save
      redirect_to questions_path(@question), notice: 'Нове питання створено!'
    else
      render :new
    end
  end
  
  def update
    @question.update(question_params)
     
    redirect_to questions_path(@question), notice: 'Питання збережене!'
  end

  def destroy
    @question.destroy

    redirect_to questions_path, notice: 'Питання видалене!'
  end

  def show
    @question = current_user.questions.find(params[:id])
  end

  def index 
    if current_user
      @questions = current_user.questions
    else
      redirect_to new_user_path
    end
  end  

  def new
    @question = current_user.questions.build
  end

  def edit
      
  end

  private

  def question_params
    params.require(:question).permit(:body, :user_id)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Ви увійшли на сайт'
    else
      flash.now[:alert] = "Неправильний email або пароль"

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Ви вийшли з акаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to questions_path, notice: 'Ви успішно зареєструвались!'
    else
      flash.now[:alert] = 'Ви неправильно заповнили поле форми реєстрації'

      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path, notice: 'Дані користувача обновлено'
    else
      flash.now[:alert] = 'При спробі зберегти користувача виникли помилки'

      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])

    if current_user == @user
      @user.destroy
      session.destroy
      redirect_to root_path, notice: 'Ваш обліковий запис був успішно видалений'
    elsif current_user.admin?
      @user.destroy
      redirect_to admins_page_path, notice: 'Користувач видалений'
    end
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions
  end

  def admin_update_role
    @user = User.find(params[:id])
    if @user.update(admin_params)
      redirect_to admins_page_path, notice: 'Роль користувача оновлено'
    else
      redirect_to admins_page_path, alert: 'Не вдалося оновити роль користувача'
    end
  end

  private

  def  user_params 
    params.require(:user).permit(
    :name, :nickname, :email, :password, :password_confirmation, :role
    )
  end

  def admin_params
    params.require(:user).permit(:admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)
    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

# код скланятора

app/views/admins/_form.html.erb
<div class="title-sm question-sm">
  <div class="mt-lg">
    <%= content_tag 'span', "@#{user.nickname}" %>
  </div>

  <% if user.present? %>
  <div class="title-sm question">
      <%= button_to fa_icon('trash-o'), user_path(user), method: :delete,
        form: { data: { turbo_confirm: "Ви впевненні, що хочете видалити користувача \"@#{user.nickname}\"?"}},
        class: 'text-red text-sm mr-sm' %>
      <%= form_with model: user, url: admin_update_role_user_path(user), method:  :put, local: true do |f| %> 
          <%= f.check_box :admin, { checked: user.admin } %>
          <%= f.label :admin, "Адміністратор", class: 'text-sm'%>
          <%= f.submit 'Зберегти', class: 'button button-main'%>
      <% end %> 
  </div>
  <% end %>
</div>

app/views/admins/page.html.erb
<div class="container mb-sm">
  <h2 class="title-lg">
    <%= @users.count %>
    <%= inclination(@users.count, 'зареєстрований користувач', 'зареєстровані користувачі', 'зареєстрованих користувачів') %>
  </h2>
</div>

<% if @users.any? %>
  <% @users.each do |user| %>
    <div class="container">
      <%= render 'form', user: user %>
    </div>
  <% end %>
<% else %>
  <p>Наразі немає зареєстрованих користувачів.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/71ade3bd8c.js" crossorigin="anonymous"></script>
 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar">
        <div class="logo">
          <p class="title-sm text-bold"><%= link_to 'Система управління', root_path%></p>
        </div>  
          <div>
            <% if current_user.present? %>
              <% if current_user.admin? %>
                <%= link_to "Сторінка адміністратора", admins_page_path, class: 'button button-yellow mr-sm' %>
              <% end %>
              <%= content_tag 'span', "@#{current_user.nickname}", class: 'mr-sm' %>
              <%= link_to fa_icon('pencil'), edit_user_path(current_user), class: 'mr-sm',
              title: 'Змінити дані'%>
              <%= button_to fa_icon('sign-out'), session_path, method: :delete, class: 'mr-sm',
              title: 'Вийти з акаунту'%>
            <% else %>  
              <div class="buttons">
                <%= link_to 'Реєстрація', new_user_path, class: 'button button-yellow mr-sm'%>
                <%= link_to 'Вхід', new_session_path, class: 'button button-yellow' %>
              </div>
            <% end %>  
          </div>  
      </div>

      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<% @question = current_user.questions.build %> 

<%= form_with model: @question do |form| %>
  <p> <%= form.label :body, 'Текст завдання:' %></p>
  <p> <%= form.text_area :body, rows: 5, class: 'form-text-area'%></p>

 <p class="mt"> <%= form.label :user_id, 'Виберіть користувача:' %></p>
<p>
  <%= form.collection_select :user_id, User.where.not(id: current_user.id), :id, :nickname, 
  { prompt: 'Виберіть користувача' }, { class: 'form-select' } %>
</p>

  <p class="mt"> <%= form.submit 'Зберегти', class: 'button button-main'%></p>
<% end %> 


app/views/questions/_form2.html.erb
<% @question = current_user.questions.build %> 

<%= form_with model: @question do |form| %>
  <p> <%= form.label :body, 'Текст завдання:' %></p>
  <p> <%= form.text_area :body, rows: 5, class: 'form-text-area'%></p>
  <p class="mt"> <%= form.submit 'Зберегти', class: 'button button-main'%></p>
<% end %> 

app/views/questions/_question.html.erb
<div class="mb-sm">
    <%= question.body %>
</div>

<div class="text-sm question-footer">
  <div class="text-grey">
    <% if question.created_at.present? %>
      <%= l(question.created_at, format: :short) %>
    <% else %>
      Дата створення відсутня
    <% end %>
  </div>


  <% if question.id.present? %>
    <div>
      <%= link_to fa_icon('pencil'), edit_question_path(question), title: 'Змінити завдання' %>
      <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, title: 'Видалити завдання' %>
    </div>
  <% else %>
    <div>Завдання не збережене</div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редагування завдання</h2>
  <%= form_with model: @question do |form| %>
    <p> <%= form.label :body, 'Текст завдання:' %></p>
    <p> <%= form.text_area :body, rows: 5, class: 'form-text-area'%></p>
    <p class="mt-lg">
      <%= form.submit 'Зберегти', class: 'button button-main' %>
    </p>
  <% end %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <p>
    <%= link_to "Доручити завдання іншому користувачу", new_question_path, class: 'button button-main'%>
  </p>
  
  <p class="container">
    <%= render 'form2', question: @question %>
  </p>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'завдання', 'завдання', 'завдань') %>
  </h2>
</div>

  <% if @questions.any? %>
    <% @questions.each do |question| %>
      <div class="mt-sm container">
        <%= render 'question', question: question %>
      </div>
    <% end %>
  <% else %>
    <p>Наразі у вас немає завдань. Ви можете створити нове завдання.</p>
  <% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Нове завання</h2>
<p class="mb-sm"> <%= link_to "Всі завання", questions_path %> </p>

  <%= render 'form', question: @question %>

</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редагування користувача</h2>
  
   <% if @user.errors.any? %>
    <div class="mt">  
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>
  
  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Ім`я' %></p>
      <p><%= form.text_field :name, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :nickname, 'Нік на сайті'%></p>
      <p><%= form.text_field :nickname, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field'%></p>

      <p class="mt-lg text-sm"> Якщо не хочете змінювати пароль - залиште ці поля пустими</p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field'%></p>

      <p class="mt-lg">
      <%= form.submit 'Зберегти', class: 'button button-main' %>
      <span class="text-sm"> або <%= link_to "повернутись", :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to "Видалити профіль", user_path(@user),
      method: :delete,
      form: {data: {turbo_confirm: "Ви впевненні, що хочете видалити свій профіль?"}},
    class: 'text-red text-sm' %>
  </div>
</div>
    

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Приєднуйся і питай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">  
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false}  do |form| %>
      <p><%= form.label :name, 'Ваше iм`я' %></p>
      <p><%= form.text_field :name, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :nickname, 'Нік на сайті'%></p>
      <p><%= form.text_field :nickname, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field'%></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field'%></p>

      <p class="mt-lg"><%= form.submit 'Зареєструватись', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>